export default {
  status: true,
  data: [
    {
      nidn: "0027086405",
      nip: "-",
      nama: "Abd. Rahim",
      namal: "Dr. Abd. Rahim, SE, M.Pd.",
      base: 3,
      level: 3,
      status: 1,
    },
    {
      nidn: "0017087110",
      nip: "",
      nama: "Abdul Azis",
      namal: "Dr. Ir. Abdul Azis, S.Pd.,M.Pd., M.T., IPM.",
      base: 1,
      level: 3,
      status: 2,
    },
    {
      nidn: "0005058802",
      nip: "",
      nama: "Abdul Haliq",
      namal: "Dr. Abdul Haliq, S.Pd., M.Pd.",
      base: 1,
      level: 3,
      status: 3,
    },
    {
      nidn: "0017087107",
      nip: "",
      nama: "Andi Agussalim Aj.",
      namal: "Dr. Andi Agussalim Aj., M.Hum.",
      base: 3,
      level: 3,
      status: 0,
    },
    {
      nidn: "0011057406",
      nip: "",
      nama: "Andi Fatimah Yunus",
      namal: "Andi Fatimah Yunus, M.Pd.",
      base: 3,
      level: 3,
      status: 0,
    },
    {
      nidn: "0927028401",
      nip: "",
      nama: "Andi Sahtiani Jahrir",
      namal: "Dr. Andi Sahtiani Jahrir, S.Pd., M.Pd.",
      base: 1,
      level: 3,
      status: 0,
    },
    {
      nidn: "0029046408",
      nip: "",
      nama: "Anshari",
      namal: "Prof. Dr. Anshari, M.Hum.",
      base: 5,
      level: 3,
      status: 0,
    },
    {
      nidn: "0028086908",
      nip: "",
      nama: "Asia M.",
      namal: "Dr. Asia M., S.S.,M.Pd.",
      base: 3,
      level: 3,
      status: 0,
    },
    {
      nidn: "0911038503",
      nip: "-",
      nama: "Asis Nojeng",
      namal: "Dr. Asis Nojeng, S.Pd, M.Pd.",
      base: 1,
      level: 3,
      status: 1,
    },
    {
      nidn: "0031057205",
      nip: "",
      nama: "Aslan Abidin",
      namal: "Dr. Aslan Abidin, S.S., M.Hum.",
      base: 2,
      level: 3,
      status: 0,
    },
    {
      nidn: "0012098908",
      nip: "-",
      nama: "Asri Ismail",
      namal: "Asri Ismail, S.Pd., M.Pd.",
      base: 3,
      level: 3,
      status: 1,
    },
    {
      nidn: "0029077905",
      nip: "",
      nama: "Aswati Asri",
      namal: "Aswati Asri, S.Pd., M.Pd.",
      base: 3,
      level: 3,
      status: 0,
    },
    {
      nidn: "0010117306",
      nip: "",
      nama: "Azis",
      namal: "Prof. Dr. Azis, S.Pd., M.Pd.",
      base: 1,
      level: 3,
      status: 0,
    },
    {
      nidn: "0909087802",
      nip: "",
      nama: "Baharman",
      namal: "Dr. Baharman, S.S., S.Pd., M.Hum.",
      base: 1,
      level: 3,
      status: 3,
    },
    {
      nidn: "0917089002",
      nip: "",
      nama: "Bungatang",
      namal: "Bungatang, S.S, M.Hum.",
      base: 2,
      level: 0,
      status: 1,
    },
    {
      nidn: "13",
      nip: "",
      nama: "co. Bahasa Arab",
      namal: "co. Bahasa Arab",
      base: 0,
      level: 0,
      status: 0,
    },
    {
      nidn: "4",
      nip: "",
      nama: "Co. Bahasa Inggris",
      namal: "Co. Bahasa Inggris",
      base: 7,
      level: 3,
      status: 0,
    },
    {
      nidn: "0002079502",
      nip: "",
      nama: "Dedi Gunawan Saputra",
      namal: "Dedi Gunawan Saputra, S.Pd., M.M., M.Pd.",
      base: 1,
      level: 1,
      status: 1,
    },
    {
      nidn: "0028118301",
      nip: "",
      nama: "Faisal",
      namal: "Faisal, S.S., M.Hum.",
      base: 2,
      level: 3,
      status: 0,
    },
    {
      nidn: "0909128903",
      nip: "",
      nama: "Filawati",
      namal: "Filawati, S.S., M.Pd.",
      base: 1,
      level: 1,
      status: 1,
    },
    {
      nidn: "0912108902",
      nip: "",
      nama: "Fitriansal",
      namal: "Fitriansal, S.Pd., M.Pd.",
      base: 1,
      level: 1,
      status: 1,
    },
    {
      nidn: "0002055505",
      nip: "",
      nama: "H. Akmal Hamsa",
      namal: "Prof. Dr. H. Akmal Hamsa, M.Pd.",
      base: 5,
      level: 3,
      status: 0,
    },
    {
      nidn: "0030126012",
      nip: "",
      nama: "H. Muhammad Rapi ",
      namal: "Prof. Dr. H. Muhammad Rapi , M.S.",
      base: 5,
      level: 3,
      status: 0,
    },
    {
      nidn: "0031127506",
      nip: "",
      nama: "H. Muhammad Saleh",
      namal: "Dr. H. Muhammad Saleh, S.Pd., M.Pd.",
      base: 1,
      level: 3,
      status: 0,
    },
    {
      nidn: "0025107203",
      nip: "",
      nama: "Hajrah",
      namal: "Dr. Hajrah, S.S., M.Pd.",
      base: 2,
      level: 3,
      status: 0,
    },
    {
      nidn: "0918068601",
      nip: "1",
      nama: "Hasriani",
      namal: "Dr.  Hasriani, S.Pd., M.Pd.",
      base: 1,
      level: 3,
      status: 0,
    },
    {
      nidn: "0019096015",
      nip: "",
      nama: "Hj. Johar Amir",
      namal: "Prof. Dr. Hj. Johar Amir, M.Hum.",
      base: 4,
      level: 3,
      status: 0,
    },
    {
      nidn: "0031126445",
      nip: "",
      nama: "Hj. Kembong Daeng",
      namal: "Prof. Dr. Hj. Kembong Daeng, M.Hum.",
      base: 3,
      level: 3,
      status: 0,
    },
    {
      nidn: "0024117104",
      nip: "",
      nama: "Idawati",
      namal: "Dr. Idawati, S.Pd., M.Pd.",
      base: 1,
      level: 3,
      status: 0,
    },
    {
      nidn: "0029089901",
      nip: "",
      nama: "Ilma Rahim",
      namal: "Ilma Rahim, S.Pd., M.Pd.",
      base: 1,
      level: 1,
      status: 1,
    },
    {
      nidn: "0010018704",
      nip: "",
      nama: "Irma Satriani",
      namal: "Irma Satriani, S.S., M.A.",
      base: 3,
      level: 3,
      status: 3,
    },
    {
      nidn: "0915018704",
      nip: "",
      nama: "Ita Rosvita",
      namal: "Ita Rosvita, S.S., M.Hum.",
      base: 1,
      level: 1,
      status: 1,
    },
    {
      nidn: "0010036805",
      nip: "",
      nama: "Juanda",
      namal: "Dr. Juanda, M.Hum.",
      base: 2,
      level: 3,
      status: 0,
    },
    {
      nidn: "0012026704",
      nip: "",
      nama: "Mahmudah",
      namal: "Dr. Mahmudah, M.Hum.",
      base: 4,
      level: 3,
      status: 0,
    },
    {
      nidn: "0031126337",
      nip: "",
      nama: "Mayong",
      namal: "Dr. Mayong, M.Pd.",
      base: 5,
      level: 3,
      status: 0,
    },
    {
      nidn: "1",
      nip: "",
      nama: "MKDU PAI",
      namal: "MKDU PAI",
      base: 7,
      level: 3,
      status: 0,
    },
    {
      nidn: "panca01",
      nip: "",
      nama: "MKDU Pancasila",
      namal: "MKDU Pancasila",
      base: 7,
      level: 3,
      status: 0,
    },
    {
      nidn: "2",
      nip: "",
      nama: "MKDU PKN",
      namal: "MKDU PKN",
      base: 7,
      level: 1,
      status: 0,
    },
    {
      nidn: "0022049801",
      nip: "",
      nama: "Muh. Bahly Basri",
      namal: "Muh. Bahly Basri, S.Pd., M.Pd.",
      base: 1,
      level: 1,
      status: 1,
    },
    {
      nidn: "0020068907",
      nip: "",
      nama: "Muh. Syukri Gaffar",
      namal: "Muh. Syukri Gaffar, S.Pd., M.Pd.",
      base: 1,
      level: 1,
      status: 1,
    },
    {
      nidn: "0029069103",
      nip: "",
      nama: "Muhammad Alfian Tuflih",
      namal: "Muhammad Alfian Tuflih, S.S., M.Pd.",
      base: 1,
      level: 3,
      status: 0,
    },
    {
      nidn: "0016129206",
      nip: "",
      nama: "Muhammad Ilham",
      namal: "Muhammad Ilham, S.Pd., M.Pd.",
      base: 1,
      level: 1,
      status: 1,
    },
    {
      nidn: "0019017304",
      nip: "",
      nama: "Nensilianti",
      namal: "Dr. Nensilianti, S.Pd.,M.Hum.",
      base: 2,
      level: 3,
      status: 0,
    },
    {
      nidn: "0025108802",
      nip: "",
      nama: "Nurhusna",
      namal: "Dr. Nurhusna, S.Pd.,M.Pd.",
      base: 1,
      level: 3,
      status: 0,
    },
    {
      nidn: "0016065910",
      nip: "",
      nama: "Ramly",
      namal: "Prof. Dr. Ramly, M.Hum.",
      base: 5,
      level: 3,
      status: 0,
    },
    {
      nidn: "0021078709",
      nip: "",
      nama: "Ridwan",
      namal: "Ridwan, S.S., M.A.",
      base: 1,
      level: 1,
      status: 1,
    },
    {
      nidn: "0030129203",
      nip: "-",
      nama: "Rizki Herdiani",
      namal: "Rizki Herdiani, M. Pd.",
      base: 1,
      level: 3,
      status: 1,
    },
    {
      nidn: "0927038504",
      nip: "198503272019031005",
      nama: "Sakaria",
      namal: "Dr. Sakaria, S.S., S.Pd., M.Pd.",
      base: 1,
      level: 3,
      status: 1,
    },
    {
      nidn: "0008068601",
      nip: "",
      nama: "Sakinah Fitri",
      namal: "Sakinah Fitri, S.S.,S.Pd.,M.Pd.",
      base: 1,
      level: 3,
      status: 0,
    },
    {
      nidn: "0028066308",
      nip: "",
      nama: "Salam",
      namal: "Dr. Salam, M.Pd.",
      base: 5,
      level: 3,
      status: 0,
    },
    {
      nidn: "0023069601",
      nip: "-",
      nama: "Shafariana",
      namal: "Shafariana, S.Pd., M.Pd.",
      base: 3,
      level: 3,
      status: 1,
    },
    {
      nidn: "0014028002",
      nip: "",
      nama: "Suarni Syam Saguni",
      namal: "Suarni Syam Saguni, S.S.,M.Hum.",
      base: 2,
      level: 3,
      status: 0,
    },
    {
      nidn: "0016025902",
      nip: "",
      nama: "Sulastriningsih Djumingin",
      namal: "Prof. Dr. Sulastriningsih Djumingin, M.Hum.",
      base: 1,
      level: 3,
      status: 0,
    },
    {
      nidn: "0012067909",
      nip: "",
      nama: "Sultan",
      namal: "Prof. Dr. Sultan, S.Pd.,M.Pd.",
      base: 1,
      level: 3,
      status: 0,
    },
    {
      nidn: "0005079304",
      nip: "",
      nama: "Suriadi",
      namal: "Suriadi, S.Pd., M.Pd.",
      base: 1,
      level: 1,
      status: 1,
    },
    {
      nidn: "0018056510",
      nip: "",
      nama: "Syamsudduha",
      namal: "Dr. Syamsudduha, M.Hum.",
      base: 3,
      level: 3,
      status: 0,
    },
    {
      nidn: "0013016805",
      nip: "",
      nama: "Tuti Wijayanti",
      namal: "Dr. Tuti Wijayanti, M.Pd.",
      base: 1,
      level: 3,
      status: 1,
    },
    {
      nidn: "0027057506",
      nip: "",
      nama: "Usman",
      namal: "Dr. Usman, S.Pd.,M.Pd.",
      base: 4,
      level: 3,
      status: 1,
    },
  ],
};
