export default {
  status: true,
  data: [
    {
      id: 1631,
      nidn1: "0030129203",
      nidn2: "",
      namal1: "Rizki Herdiani, M. Pd.",
      namal2: null,
      kodemk: "20E01C101",
      namamk: "Linguistik Umum",
      semester: 1,
      kelas: "A",
      hari: 0,
      ruang: 0,
      masuk: null,
      sks: 3,
      prodi: "PBSI",
    },
    {
      id: 1635,
      nidn1: "0030129203",
      nidn2: "",
      namal1: "Rizki Herdiani, M. Pd.",
      namal2: null,
      kodemk: "20E01C101",
      namamk: "Linguistik Umum",
      semester: 1,
      kelas: "B",
      hari: 0,
      ruang: 0,
      masuk: null,
      sks: 3,
      prodi: "PBSI",
    },
    {
      id: 1642,
      nidn1: "0008068601",
      nidn2: "",
      namal1: "Sakinah Fitri, S.S.,S.Pd.,M.Pd.",
      namal2: null,
      kodemk: "20E01C101",
      namamk: "Linguistik Umum",
      semester: 1,
      kelas: "C",
      hari: 0,
      ruang: 0,
      masuk: null,
      sks: 3,
      prodi: "PBSI",
    },
    {
      id: 1646,
      nidn1: "0008068601",
      nidn2: "",
      namal1: "Sakinah Fitri, S.S.,S.Pd.,M.Pd.",
      namal2: null,
      kodemk: "20E01C101",
      namamk: "Linguistik Umum",
      semester: 1,
      kelas: "D",
      hari: 0,
      ruang: 0,
      masuk: null,
      sks: 3,
      prodi: "PBSI",
    },
    {
      id: 1647,
      nidn1: "0023069601",
      nidn2: "",
      namal1: "Shafariana, S.Pd., M.Pd.",
      namal2: null,
      kodemk: "20E01C101",
      namamk: "Linguistik Umum",
      semester: 1,
      kelas: "E",
      hari: 0,
      ruang: 0,
      masuk: null,
      sks: 3,
      prodi: "PBSI",
    },
    {
      id: 1648,
      nidn1: "0023069601",
      nidn2: "",
      namal1: "Shafariana, S.Pd., M.Pd.",
      namal2: null,
      kodemk: "20E01C101",
      namamk: "Linguistik Umum",
      semester: 1,
      kelas: "F",
      hari: 0,
      ruang: 0,
      masuk: null,
      sks: 3,
      prodi: "PBSI",
    },
    {
      id: 1649,
      nidn1: "0022049801",
      nidn2: "",
      namal1: "Muh. Bahly Basri, S.Pd., M.Pd.",
      namal2: null,
      kodemk: "20E01C101",
      namamk: "Linguistik Umum",
      semester: 1,
      kelas: "G",
      hari: 0,
      ruang: 0,
      masuk: null,
      sks: 3,
      prodi: "PBSI",
    },
    {
      id: 1643,
      nidn1: "0005058802",
      nidn2: "",
      namal1: "Dr. Abdul Haliq, S.Pd., M.Pd.",
      namal2: null,
      kodemk: "20E01C102",
      namamk: "Fonologi Bahasa Indonesia",
      semester: 1,
      kelas: "A",
      hari: 0,
      ruang: 0,
      masuk: null,
      sks: 3,
      prodi: "PBSI",
    },
    {
      id: 1650,
      nidn1: "0005058802",
      nidn2: "",
      namal1: "Dr. Abdul Haliq, S.Pd., M.Pd.",
      namal2: null,
      kodemk: "20E01C102",
      namamk: "Fonologi Bahasa Indonesia",
      semester: 1,
      kelas: "B",
      hari: 0,
      ruang: 0,
      masuk: null,
      sks: 3,
      prodi: "PBSI",
    },
    {
      id: 1641,
      nidn1: "0017087110",
      nidn2: "",
      namal1: "Dr. Ir. Abdul Azis, S.Pd.,M.Pd., M.T., IPM.",
      namal2: null,
      kodemk: "20E01C102",
      namamk: "Fonologi Bahasa Indonesia",
      semester: 1,
      kelas: "C",
      hari: 0,
      ruang: 0,
      masuk: null,
      sks: 3,
      prodi: "PBSI",
    },
    {
      id: 1651,
      nidn1: "0017087110",
      nidn2: "",
      namal1: "Dr. Ir. Abdul Azis, S.Pd.,M.Pd., M.T., IPM.",
      namal2: null,
      kodemk: "20E01C102",
      namamk: "Fonologi Bahasa Indonesia",
      semester: 1,
      kelas: "D",
      hari: 0,
      ruang: 0,
      masuk: null,
      sks: 3,
      prodi: "PBSI",
    },
    {
      id: 1652,
      nidn1: "0008068601",
      nidn2: "",
      namal1: "Sakinah Fitri, S.S.,S.Pd.,M.Pd.",
      namal2: null,
      kodemk: "20E01C102",
      namamk: "Fonologi Bahasa Indonesia",
      semester: 1,
      kelas: "E",
      hari: 0,
      ruang: 0,
      masuk: null,
      sks: 3,
      prodi: "PBSI",
    },
    {
      id: 1653,
      nidn1: "0008068601",
      nidn2: "",
      namal1: "Sakinah Fitri, S.S.,S.Pd.,M.Pd.",
      namal2: null,
      kodemk: "20E01C102",
      namamk: "Fonologi Bahasa Indonesia",
      semester: 1,
      kelas: "F",
      hari: 0,
      ruang: 0,
      masuk: null,
      sks: 3,
      prodi: "PBSI",
    },
    {
      id: 1654,
      nidn1: "0020068907",
      nidn2: "",
      namal1: "Muh. Syukri Gaffar, S.Pd., M.Pd.",
      namal2: null,
      kodemk: "20E01C102",
      namamk: "Fonologi Bahasa Indonesia",
      semester: 1,
      kelas: "G",
      hari: 0,
      ruang: 0,
      masuk: null,
      sks: 3,
      prodi: "PBSI",
    },
    {
      id: 1655,
      nidn1: "0019096015",
      nidn2: "",
      namal1: "Prof. Dr. Hj. Johar Amir, M.Hum.",
      namal2: null,
      kodemk: "20E01C103",
      namamk: "Morfologi Bahasa Indonesia",
      semester: 1,
      kelas: "A",
      hari: 0,
      ruang: 0,
      masuk: null,
      sks: 3,
      prodi: "PBSI",
    },
    {
      id: 1656,
      nidn1: "0019096015",
      nidn2: "",
      namal1: "Prof. Dr. Hj. Johar Amir, M.Hum.",
      namal2: null,
      kodemk: "20E01C103",
      namamk: "Morfologi Bahasa Indonesia",
      semester: 1,
      kelas: "B",
      hari: 0,
      ruang: 0,
      masuk: null,
      sks: 3,
      prodi: "PBSI",
    },
    {
      id: 1657,
      nidn1: "0030129203",
      nidn2: "",
      namal1: "Rizki Herdiani, M. Pd.",
      namal2: null,
      kodemk: "20E01C103",
      namamk: "Morfologi Bahasa Indonesia",
      semester: 1,
      kelas: "C",
      hari: 0,
      ruang: 0,
      masuk: null,
      sks: 3,
      prodi: "PBSI",
    },
    {
      id: 1658,
      nidn1: "0030129203",
      nidn2: "",
      namal1: "Rizki Herdiani, M. Pd.",
      namal2: null,
      kodemk: "20E01C103",
      namamk: "Morfologi Bahasa Indonesia",
      semester: 1,
      kelas: "D",
      hari: 0,
      ruang: 0,
      masuk: null,
      sks: 3,
      prodi: "PBSI",
    },
    {
      id: 1659,
      nidn1: "0016065910",
      nidn2: "",
      namal1: "Prof. Dr. Ramly, M.Hum.",
      namal2: null,
      kodemk: "20E01C103",
      namamk: "Morfologi Bahasa Indonesia",
      semester: 1,
      kelas: "E",
      hari: 0,
      ruang: 0,
      masuk: null,
      sks: 3,
      prodi: "PBSI",
    },
    {
      id: 1660,
      nidn1: "0016065910",
      nidn2: "",
      namal1: "Prof. Dr. Ramly, M.Hum.",
      namal2: null,
      kodemk: "20E01C103",
      namamk: "Morfologi Bahasa Indonesia",
      semester: 1,
      kelas: "F",
      hari: 0,
      ruang: 0,
      masuk: null,
      sks: 3,
      prodi: "PBSI",
    },
    {
      id: 1661,
      nidn1: "0022049801",
      nidn2: "",
      namal1: "Muh. Bahly Basri, S.Pd., M.Pd.",
      namal2: null,
      kodemk: "20E01C103",
      namamk: "Morfologi Bahasa Indonesia",
      semester: 1,
      kelas: "G",
      hari: 0,
      ruang: 0,
      masuk: null,
      sks: 3,
      prodi: "PBSI",
    },
    {
      id: 1662,
      nidn1: "0010117306",
      nidn2: "",
      namal1: "Prof. Dr. Azis, S.Pd., M.Pd.",
      namal2: null,
      kodemk: "20E01C104",
      namamk: "Pembinaan dan Pengemb. BI",
      semester: 1,
      kelas: "A",
      hari: 0,
      ruang: 0,
      masuk: null,
      sks: 3,
      prodi: "PBSI",
    },
    {
      id: 1663,
      nidn1: "0010117306",
      nidn2: "",
      namal1: "Prof. Dr. Azis, S.Pd., M.Pd.",
      namal2: null,
      kodemk: "20E01C104",
      namamk: "Pembinaan dan Pengemb. BI",
      semester: 1,
      kelas: "B",
      hari: 0,
      ruang: 0,
      masuk: null,
      sks: 3,
      prodi: "PBSI",
    },
    {
      id: 1664,
      nidn1: "0918068601",
      nidn2: "",
      namal1: "Dr.  Hasriani, S.Pd., M.Pd.",
      namal2: null,
      kodemk: "20E01C104",
      namamk: "Pembinaan dan Pengemb. BI",
      semester: 1,
      kelas: "C",
      hari: 0,
      ruang: 0,
      masuk: null,
      sks: 3,
      prodi: "PBSI",
    },
    {
      id: 1665,
      nidn1: "0023069601",
      nidn2: "",
      namal1: "Shafariana, S.Pd., M.Pd.",
      namal2: null,
      kodemk: "20E01C104",
      namamk: "Pembinaan dan Pengemb. BI",
      semester: 1,
      kelas: "D",
      hari: 0,
      ruang: 0,
      masuk: null,
      sks: 3,
      prodi: "PBSI",
    },
    {
      id: 1666,
      nidn1: "0012098908",
      nidn2: "",
      namal1: "Asri Ismail, S.Pd., M.Pd.",
      namal2: null,
      kodemk: "20E01C104",
      namamk: "Pembinaan dan Pengemb. BI",
      semester: 1,
      kelas: "E",
      hari: 0,
      ruang: 0,
      masuk: null,
      sks: 3,
      prodi: "PBSI",
    },
    {
      id: 1667,
      nidn1: "0012098908",
      nidn2: "",
      namal1: "Asri Ismail, S.Pd., M.Pd.",
      namal2: null,
      kodemk: "20E01C104",
      namamk: "Pembinaan dan Pengemb. BI",
      semester: 1,
      kelas: "F",
      hari: 0,
      ruang: 0,
      masuk: null,
      sks: 3,
      prodi: "PBSI",
    },
    {
      id: 1668,
      nidn1: "0020068907",
      nidn2: "",
      namal1: "Muh. Syukri Gaffar, S.Pd., M.Pd.",
      namal2: null,
      kodemk: "20E01C104",
      namamk: "Pembinaan dan Pengemb. BI",
      semester: 1,
      kelas: "G",
      hari: 0,
      ruang: 0,
      masuk: null,
      sks: 3,
      prodi: "PBSI",
    },
    {
      id: 1669,
      nidn1: "0030126012",
      nidn2: "",
      namal1: "Prof. Dr. H. Muhammad Rapi , M.S.",
      namal2: null,
      kodemk: "20E01C105",
      namamk: "Sejarah Sastra",
      semester: 1,
      kelas: "A",
      hari: 0,
      ruang: 0,
      masuk: null,
      sks: 2,
      prodi: "PBSI",
    },
    {
      id: 1670,
      nidn1: "0030126012",
      nidn2: "",
      namal1: "Prof. Dr. H. Muhammad Rapi , M.S.",
      namal2: null,
      kodemk: "20E01C105",
      namamk: "Sejarah Sastra",
      semester: 1,
      kelas: "B",
      hari: 0,
      ruang: 0,
      masuk: null,
      sks: 2,
      prodi: "PBSI",
    },
    {
      id: 1671,
      nidn1: "0030126012",
      nidn2: "",
      namal1: "Prof. Dr. H. Muhammad Rapi , M.S.",
      namal2: null,
      kodemk: "20E01C105",
      namamk: "Sejarah Sastra",
      semester: 1,
      kelas: "C",
      hari: 0,
      ruang: 0,
      masuk: null,
      sks: 2,
      prodi: "PBSI",
    },
    {
      id: 1672,
      nidn1: "0911038503",
      nidn2: "",
      namal1: "Dr. Asis Nojeng, S.Pd, M.Pd.",
      namal2: null,
      kodemk: "20E01C105",
      namamk: "Sejarah Sastra",
      semester: 1,
      kelas: "D",
      hari: 0,
      ruang: 0,
      masuk: null,
      sks: 2,
      prodi: "PBSI",
    },
    {
      id: 1673,
      nidn1: "0911038503",
      nidn2: "",
      namal1: "Dr. Asis Nojeng, S.Pd, M.Pd.",
      namal2: null,
      kodemk: "20E01C105",
      namamk: "Sejarah Sastra",
      semester: 1,
      kelas: "E",
      hari: 0,
      ruang: 0,
      masuk: null,
      sks: 2,
      prodi: "PBSI",
    },
    {
      id: 1674,
      nidn1: "0029046408",
      nidn2: "",
      namal1: "Prof. Dr. Anshari, M.Hum.",
      namal2: null,
      kodemk: "20E01C105",
      namamk: "Sejarah Sastra",
      semester: 1,
      kelas: "F",
      hari: 0,
      ruang: 0,
      masuk: null,
      sks: 2,
      prodi: "PBSI",
    },
    {
      id: 1675,
      nidn1: "0029046408",
      nidn2: "",
      namal1: "Prof. Dr. Anshari, M.Hum.",
      namal2: null,
      kodemk: "20E01C105",
      namamk: "Sejarah Sastra",
      semester: 1,
      kelas: "G",
      hari: 0,
      ruang: 0,
      masuk: null,
      sks: 2,
      prodi: "PBSI",
    },
    {
      id: 1676,
      nidn1: "0029046408",
      nidn2: "",
      namal1: "Prof. Dr. Anshari, M.Hum.",
      namal2: null,
      kodemk: "20E01C106",
      namamk: "Teori   Sastra",
      semester: 1,
      kelas: "A",
      hari: 0,
      ruang: 0,
      masuk: null,
      sks: 2,
      prodi: "PBSI",
    },
    {
      id: 1677,
      nidn1: "0029046408",
      nidn2: "",
      namal1: "Prof. Dr. Anshari, M.Hum.",
      namal2: null,
      kodemk: "20E01C106",
      namamk: "Teori   Sastra",
      semester: 1,
      kelas: "B",
      hari: 0,
      ruang: 0,
      masuk: null,
      sks: 2,
      prodi: "PBSI",
    },
    {
      id: 1678,
      nidn1: "0029046408",
      nidn2: "",
      namal1: "Prof. Dr. Anshari, M.Hum.",
      namal2: null,
      kodemk: "20E01C106",
      namamk: "Teori   Sastra",
      semester: 1,
      kelas: "C",
      hari: 0,
      ruang: 0,
      masuk: null,
      sks: 2,
      prodi: "PBSI",
    },
    {
      id: 1679,
      nidn1: "0909087802",
      nidn2: "",
      namal1: "Dr. Baharman, S.S., S.Pd., M.Hum.",
      namal2: null,
      kodemk: "20E01C106",
      namamk: "Teori   Sastra",
      semester: 1,
      kelas: "D",
      hari: 0,
      ruang: 0,
      masuk: null,
      sks: 2,
      prodi: "PBSI",
    },
    {
      id: 1680,
      nidn1: "0909087802",
      nidn2: "",
      namal1: "Dr. Baharman, S.S., S.Pd., M.Hum.",
      namal2: null,
      kodemk: "20E01C106",
      namamk: "Teori   Sastra",
      semester: 1,
      kelas: "E",
      hari: 0,
      ruang: 0,
      masuk: null,
      sks: 2,
      prodi: "PBSI",
    },
    {
      id: 1681,
      nidn1: "0909087802",
      nidn2: "",
      namal1: "Dr. Baharman, S.S., S.Pd., M.Hum.",
      namal2: null,
      kodemk: "20E01C106",
      namamk: "Teori   Sastra",
      semester: 1,
      kelas: "F",
      hari: 0,
      ruang: 0,
      masuk: null,
      sks: 2,
      prodi: "PBSI",
    },
    {
      id: 1682,
      nidn1: "0005079304",
      nidn2: "",
      namal1: "Suriadi, S.Pd., M.Pd.",
      namal2: null,
      kodemk: "20E01C106",
      namamk: "Teori   Sastra",
      semester: 1,
      kelas: "G",
      hari: 0,
      ruang: 0,
      masuk: null,
      sks: 2,
      prodi: "PBSI",
    },
    {
      id: 1683,
      nidn1: "4",
      nidn2: "",
      namal1: "Co. Bahasa Inggris",
      namal2: null,
      kodemk: "20E01C107",
      namamk: "Bahasa Inggris",
      semester: 1,
      kelas: "A",
      hari: 0,
      ruang: 0,
      masuk: null,
      sks: 2,
      prodi: "PBSI",
    },
    {
      id: 1684,
      nidn1: "4",
      nidn2: "",
      namal1: "Co. Bahasa Inggris",
      namal2: null,
      kodemk: "20E01C107",
      namamk: "Bahasa Inggris",
      semester: 1,
      kelas: "B",
      hari: 0,
      ruang: 0,
      masuk: null,
      sks: 2,
      prodi: "PBSI",
    },
    {
      id: 1685,
      nidn1: "4",
      nidn2: "",
      namal1: "Co. Bahasa Inggris",
      namal2: null,
      kodemk: "20E01C107",
      namamk: "Bahasa Inggris",
      semester: 1,
      kelas: "C",
      hari: 0,
      ruang: 0,
      masuk: null,
      sks: 2,
      prodi: "PBSI",
    },
    {
      id: 1686,
      nidn1: "4",
      nidn2: "",
      namal1: "Co. Bahasa Inggris",
      namal2: null,
      kodemk: "20E01C107",
      namamk: "Bahasa Inggris",
      semester: 1,
      kelas: "D",
      hari: 0,
      ruang: 0,
      masuk: null,
      sks: 2,
      prodi: "PBSI",
    },
    {
      id: 1687,
      nidn1: "4",
      nidn2: "",
      namal1: "Co. Bahasa Inggris",
      namal2: null,
      kodemk: "20E01C107",
      namamk: "Bahasa Inggris",
      semester: 1,
      kelas: "E",
      hari: 0,
      ruang: 0,
      masuk: null,
      sks: 2,
      prodi: "PBSI",
    },
    {
      id: 1688,
      nidn1: "4",
      nidn2: "",
      namal1: "Co. Bahasa Inggris",
      namal2: null,
      kodemk: "20E01C107",
      namamk: "Bahasa Inggris",
      semester: 1,
      kelas: "F",
      hari: 0,
      ruang: 0,
      masuk: null,
      sks: 2,
      prodi: "PBSI",
    },
    {
      id: 1689,
      nidn1: "4",
      nidn2: "",
      namal1: "Co. Bahasa Inggris",
      namal2: null,
      kodemk: "20E01C107",
      namamk: "Bahasa Inggris",
      semester: 1,
      kelas: "G",
      hari: 0,
      ruang: 0,
      masuk: null,
      sks: 2,
      prodi: "PBSI",
    },
    {
      id: 1704,
      nidn1: "0031126337",
      nidn2: "",
      namal1: "Dr. Mayong, M.Pd.",
      namal2: null,
      kodemk: "20E01C323",
      namamk: "Pengantar Pendidikan",
      semester: 3,
      kelas: "A",
      hari: 0,
      ruang: 0,
      masuk: null,
      sks: 2,
      prodi: "PBSI",
    },
    {
      id: 1705,
      nidn1: "0031126337",
      nidn2: "",
      namal1: "Dr. Mayong, M.Pd.",
      namal2: null,
      kodemk: "20E01C323",
      namamk: "Pengantar Pendidikan",
      semester: 3,
      kelas: "B",
      hari: 0,
      ruang: 0,
      masuk: null,
      sks: 2,
      prodi: "PBSI",
    },
    {
      id: 1706,
      nidn1: "0031126337",
      nidn2: "",
      namal1: "Dr. Mayong, M.Pd.",
      namal2: null,
      kodemk: "20E01C323",
      namamk: "Pengantar Pendidikan",
      semester: 3,
      kelas: "C",
      hari: 0,
      ruang: 0,
      masuk: null,
      sks: 2,
      prodi: "PBSI",
    },
    {
      id: 1707,
      nidn1: "0025108802",
      nidn2: "",
      namal1: "Dr. Nurhusna, S.Pd.,M.Pd.",
      namal2: null,
      kodemk: "20E01C323",
      namamk: "Pengantar Pendidikan",
      semester: 3,
      kelas: "D",
      hari: 0,
      ruang: 0,
      masuk: null,
      sks: 2,
      prodi: "PBSI",
    },
    {
      id: 1708,
      nidn1: "0008068601",
      nidn2: "",
      namal1: "Sakinah Fitri, S.S.,S.Pd.,M.Pd.",
      namal2: null,
      kodemk: "20E01C323",
      namamk: "Pengantar Pendidikan",
      semester: 3,
      kelas: "E",
      hari: 0,
      ruang: 0,
      masuk: null,
      sks: 2,
      prodi: "PBSI",
    },
    {
      id: 1709,
      nidn1: "",
      nidn2: "",
      namal1: null,
      namal2: null,
      kodemk: "20E01C323",
      namamk: "Pengantar Pendidikan",
      semester: 3,
      kelas: "F",
      hari: 0,
      ruang: 0,
      masuk: null,
      sks: 2,
      prodi: "PBSI",
    },
    {
      id: 1710,
      nidn1: "0909087802",
      nidn2: "",
      namal1: "Dr. Baharman, S.S., S.Pd., M.Hum.",
      namal2: null,
      kodemk: "20E01C324",
      namamk: "Perkembangan Peserta Didik",
      semester: 3,
      kelas: "A",
      hari: 0,
      ruang: 0,
      masuk: null,
      sks: 2,
      prodi: "PBSI",
    },
    {
      id: 1711,
      nidn1: "0909087802",
      nidn2: "",
      namal1: "Dr. Baharman, S.S., S.Pd., M.Hum.",
      namal2: null,
      kodemk: "20E01C324",
      namamk: "Perkembangan Peserta Didik",
      semester: 3,
      kelas: "B",
      hari: 0,
      ruang: 0,
      masuk: null,
      sks: 2,
      prodi: "PBSI",
    },
    {
      id: 1712,
      nidn1: "0020068907",
      nidn2: "",
      namal1: "Muh. Syukri Gaffar, S.Pd., M.Pd.",
      namal2: null,
      kodemk: "20E01C324",
      namamk: "Perkembangan Peserta Didik",
      semester: 3,
      kelas: "C",
      hari: 0,
      ruang: 0,
      masuk: null,
      sks: 2,
      prodi: "PBSI",
    },
    {
      id: 1713,
      nidn1: "0013016805",
      nidn2: "",
      namal1: "Dr. Tuti Wijayanti, M.Pd.",
      namal2: null,
      kodemk: "20E01C324",
      namamk: "Perkembangan Peserta Didik",
      semester: 3,
      kelas: "D",
      hari: 0,
      ruang: 0,
      masuk: null,
      sks: 2,
      prodi: "PBSI",
    },
    {
      id: 1714,
      nidn1: "0013016805",
      nidn2: "",
      namal1: "Dr. Tuti Wijayanti, M.Pd.",
      namal2: null,
      kodemk: "20E01C324",
      namamk: "Perkembangan Peserta Didik",
      semester: 3,
      kelas: "E",
      hari: 0,
      ruang: 0,
      masuk: null,
      sks: 2,
      prodi: "PBSI",
    },
    {
      id: 1715,
      nidn1: "",
      nidn2: "",
      namal1: null,
      namal2: null,
      kodemk: "20E01C324",
      namamk: "Perkembangan Peserta Didik",
      semester: 3,
      kelas: "F",
      hari: 0,
      ruang: 0,
      masuk: null,
      sks: 2,
      prodi: "PBSI",
    },
    {
      id: 1716,
      nidn1: "0024117104",
      nidn2: "",
      namal1: "Dr. Idawati, S.Pd., M.Pd.",
      namal2: null,
      kodemk: "20E01C325",
      namamk: "Profesi Kependidikan",
      semester: 3,
      kelas: "A",
      hari: 0,
      ruang: 0,
      masuk: null,
      sks: 2,
      prodi: "PBSI",
    },
    {
      id: 1717,
      nidn1: "0024117104",
      nidn2: "",
      namal1: "Dr. Idawati, S.Pd., M.Pd.",
      namal2: null,
      kodemk: "20E01C325",
      namamk: "Profesi Kependidikan",
      semester: 3,
      kelas: "B",
      hari: 0,
      ruang: 0,
      masuk: null,
      sks: 2,
      prodi: "PBSI",
    },
    {
      id: 1718,
      nidn1: "0909087802",
      nidn2: "",
      namal1: "Dr. Baharman, S.S., S.Pd., M.Hum.",
      namal2: null,
      kodemk: "20E01C325",
      namamk: "Profesi Kependidikan",
      semester: 3,
      kelas: "C",
      hari: 0,
      ruang: 0,
      masuk: null,
      sks: 2,
      prodi: "PBSI",
    },
    {
      id: 1719,
      nidn1: "0909087802",
      nidn2: "",
      namal1: "Dr. Baharman, S.S., S.Pd., M.Hum.",
      namal2: null,
      kodemk: "20E01C325",
      namamk: "Profesi Kependidikan",
      semester: 3,
      kelas: "D",
      hari: 0,
      ruang: 0,
      masuk: null,
      sks: 2,
      prodi: "PBSI",
    },
    {
      id: 1720,
      nidn1: "0013016805",
      nidn2: "",
      namal1: "Dr. Tuti Wijayanti, M.Pd.",
      namal2: null,
      kodemk: "20E01C325",
      namamk: "Profesi Kependidikan",
      semester: 3,
      kelas: "E",
      hari: 0,
      ruang: 0,
      masuk: null,
      sks: 2,
      prodi: "PBSI",
    },
    {
      id: 1721,
      nidn1: "",
      nidn2: "",
      namal1: null,
      namal2: null,
      kodemk: "20E01C325",
      namamk: "Profesi Kependidikan",
      semester: 3,
      kelas: "F",
      hari: 0,
      ruang: 0,
      masuk: null,
      sks: 2,
      prodi: "PBSI",
    },
    {
      id: 1722,
      nidn1: "0005058802",
      nidn2: "",
      namal1: "Dr. Abdul Haliq, S.Pd., M.Pd.",
      namal2: null,
      kodemk: "20E01C326",
      namamk: "Telaah Kurikulum dan Buku Teks",
      semester: 3,
      kelas: "A",
      hari: 0,
      ruang: 0,
      masuk: null,
      sks: 3,
      prodi: "PBSI",
    },
    {
      id: 1723,
      nidn1: "0005058802",
      nidn2: "",
      namal1: "Dr. Abdul Haliq, S.Pd., M.Pd.",
      namal2: null,
      kodemk: "20E01C326",
      namamk: "Telaah Kurikulum dan Buku Teks",
      semester: 3,
      kelas: "B",
      hari: 0,
      ruang: 0,
      masuk: null,
      sks: 3,
      prodi: "PBSI",
    },
    {
      id: 1724,
      nidn1: "0027057506",
      nidn2: "",
      namal1: "Dr. Usman, S.Pd.,M.Pd.",
      namal2: null,
      kodemk: "20E01C326",
      namamk: "Telaah Kurikulum dan Buku Teks",
      semester: 3,
      kelas: "C",
      hari: 0,
      ruang: 0,
      masuk: null,
      sks: 3,
      prodi: "PBSI",
    },
    {
      id: 1725,
      nidn1: "0027057506",
      nidn2: "",
      namal1: "Dr. Usman, S.Pd.,M.Pd.",
      namal2: null,
      kodemk: "20E01C326",
      namamk: "Telaah Kurikulum dan Buku Teks",
      semester: 3,
      kelas: "D",
      hari: 0,
      ruang: 0,
      masuk: null,
      sks: 3,
      prodi: "PBSI",
    },
    {
      id: 1726,
      nidn1: "0027057506",
      nidn2: "",
      namal1: "Dr. Usman, S.Pd.,M.Pd.",
      namal2: null,
      kodemk: "20E01C326",
      namamk: "Telaah Kurikulum dan Buku Teks",
      semester: 3,
      kelas: "E",
      hari: 0,
      ruang: 0,
      masuk: null,
      sks: 3,
      prodi: "PBSI",
    },
    {
      id: 1727,
      nidn1: "",
      nidn2: "",
      namal1: null,
      namal2: null,
      kodemk: "20E01C326",
      namamk: "Telaah Kurikulum dan Buku Teks",
      semester: 3,
      kelas: "F",
      hari: 0,
      ruang: 0,
      masuk: null,
      sks: 3,
      prodi: "PBSI",
    },
    {
      id: 1728,
      nidn1: "0028066308",
      nidn2: "",
      namal1: "Dr. Salam, M.Pd.",
      namal2: null,
      kodemk: "20E01C327",
      namamk: "Teks dalam Bahasa Indonesia",
      semester: 3,
      kelas: "A",
      hari: 0,
      ruang: 0,
      masuk: null,
      sks: 3,
      prodi: "PBSI",
    },
    {
      id: 1729,
      nidn1: "0028066308",
      nidn2: "",
      namal1: "Dr. Salam, M.Pd.",
      namal2: null,
      kodemk: "20E01C327",
      namamk: "Teks dalam Bahasa Indonesia",
      semester: 3,
      kelas: "B",
      hari: 0,
      ruang: 0,
      masuk: null,
      sks: 3,
      prodi: "PBSI",
    },
    {
      id: 1730,
      nidn1: "0016025902",
      nidn2: "",
      namal1: "Prof. Dr. Sulastriningsih Djumingin, M.Hum.",
      namal2: null,
      kodemk: "20E01C327",
      namamk: "Teks dalam Bahasa Indonesia",
      semester: 3,
      kelas: "C",
      hari: 0,
      ruang: 0,
      masuk: null,
      sks: 3,
      prodi: "PBSI",
    },
    {
      id: 1731,
      nidn1: "0016025902",
      nidn2: "",
      namal1: "Prof. Dr. Sulastriningsih Djumingin, M.Hum.",
      namal2: null,
      kodemk: "20E01C327",
      namamk: "Teks dalam Bahasa Indonesia",
      semester: 3,
      kelas: "D",
      hari: 0,
      ruang: 0,
      masuk: null,
      sks: 3,
      prodi: "PBSI",
    },
    {
      id: 1732,
      nidn1: "0016025902",
      nidn2: "",
      namal1: "Prof. Dr. Sulastriningsih Djumingin, M.Hum.",
      namal2: null,
      kodemk: "20E01C327",
      namamk: "Teks dalam Bahasa Indonesia",
      semester: 3,
      kelas: "E",
      hari: 0,
      ruang: 0,
      masuk: null,
      sks: 3,
      prodi: "PBSI",
    },
    {
      id: 1733,
      nidn1: "",
      nidn2: "",
      namal1: null,
      namal2: null,
      kodemk: "20E01C327",
      namamk: "Teks dalam Bahasa Indonesia",
      semester: 3,
      kelas: "F",
      hari: 0,
      ruang: 0,
      masuk: null,
      sks: 3,
      prodi: "PBSI",
    },
    {
      id: 1734,
      nidn1: "0012067909",
      nidn2: "",
      namal1: "Prof. Dr. Sultan, S.Pd.,M.Pd.",
      namal2: null,
      kodemk: "20E01C328",
      namamk: "Keterampilan Membaca",
      semester: 3,
      kelas: "A",
      hari: 0,
      ruang: 0,
      masuk: null,
      sks: 3,
      prodi: "PBSI",
    },
    {
      id: 1735,
      nidn1: "0012067909",
      nidn2: "",
      namal1: "Prof. Dr. Sultan, S.Pd.,M.Pd.",
      namal2: null,
      kodemk: "20E01C328",
      namamk: "Keterampilan Membaca",
      semester: 3,
      kelas: "B",
      hari: 0,
      ruang: 0,
      masuk: null,
      sks: 3,
      prodi: "PBSI",
    },
    {
      id: 1736,
      nidn1: "0012067909",
      nidn2: "",
      namal1: "Prof. Dr. Sultan, S.Pd.,M.Pd.",
      namal2: null,
      kodemk: "20E01C328",
      namamk: "Keterampilan Membaca",
      semester: 3,
      kelas: "C",
      hari: 0,
      ruang: 0,
      masuk: null,
      sks: 3,
      prodi: "PBSI",
    },
    {
      id: 1737,
      nidn1: "0025108802",
      nidn2: "",
      namal1: "Dr. Nurhusna, S.Pd.,M.Pd.",
      namal2: null,
      kodemk: "20E01C328",
      namamk: "Keterampilan Membaca",
      semester: 3,
      kelas: "D",
      hari: 0,
      ruang: 0,
      masuk: null,
      sks: 3,
      prodi: "PBSI",
    },
    {
      id: 1738,
      nidn1: "0025108802",
      nidn2: "",
      namal1: "Dr. Nurhusna, S.Pd.,M.Pd.",
      namal2: null,
      kodemk: "20E01C328",
      namamk: "Keterampilan Membaca",
      semester: 3,
      kelas: "E",
      hari: 0,
      ruang: 0,
      masuk: null,
      sks: 3,
      prodi: "PBSI",
    },
    {
      id: 1739,
      nidn1: "0002055505",
      nidn2: "",
      namal1: "Prof. Dr. H. Akmal Hamsa, M.Pd.",
      namal2: null,
      kodemk: "20E01C329",
      namamk: "Keterampilan Menulis",
      semester: 3,
      kelas: "A",
      hari: 0,
      ruang: 0,
      masuk: null,
      sks: 3,
      prodi: "PBSI",
    },
    {
      id: 1740,
      nidn1: "0002055505",
      nidn2: "",
      namal1: "Prof. Dr. H. Akmal Hamsa, M.Pd.",
      namal2: null,
      kodemk: "20E01C329",
      namamk: "Keterampilan Menulis",
      semester: 3,
      kelas: "B",
      hari: 0,
      ruang: 0,
      masuk: null,
      sks: 3,
      prodi: "PBSI",
    },
    {
      id: 1741,
      nidn1: "0002055505",
      nidn2: "",
      namal1: "Prof. Dr. H. Akmal Hamsa, M.Pd.",
      namal2: null,
      kodemk: "20E01C329",
      namamk: "Keterampilan Menulis",
      semester: 3,
      kelas: "C",
      hari: 0,
      ruang: 0,
      masuk: null,
      sks: 3,
      prodi: "PBSI",
    },
    {
      id: 1742,
      nidn1: "0002055505",
      nidn2: "",
      namal1: "Prof. Dr. H. Akmal Hamsa, M.Pd.",
      namal2: null,
      kodemk: "20E01C329",
      namamk: "Keterampilan Menulis",
      semester: 3,
      kelas: "D",
      hari: 0,
      ruang: 0,
      masuk: null,
      sks: 3,
      prodi: "PBSI",
    },
    {
      id: 1743,
      nidn1: "0013016805",
      nidn2: "",
      namal1: "Dr. Tuti Wijayanti, M.Pd.",
      namal2: null,
      kodemk: "20E01C329",
      namamk: "Keterampilan Menulis",
      semester: 3,
      kelas: "E",
      hari: 0,
      ruang: 0,
      masuk: null,
      sks: 3,
      prodi: "PBSI",
    },
    {
      id: 1744,
      nidn1: "0031127506",
      nidn2: "",
      namal1: "Dr. H. Muhammad Saleh, S.Pd., M.Pd.",
      namal2: null,
      kodemk: "20E01C330",
      namamk: "Pragmatik",
      semester: 3,
      kelas: "A",
      hari: 0,
      ruang: 0,
      masuk: null,
      sks: 3,
      prodi: "PBSI",
    },
    {
      id: 1745,
      nidn1: "0031127506",
      nidn2: "",
      namal1: "Dr. H. Muhammad Saleh, S.Pd., M.Pd.",
      namal2: null,
      kodemk: "20E01C330",
      namamk: "Pragmatik",
      semester: 3,
      kelas: "B",
      hari: 0,
      ruang: 0,
      masuk: null,
      sks: 3,
      prodi: "PBSI",
    },
    {
      id: 1746,
      nidn1: "0010117306",
      nidn2: "",
      namal1: "Prof. Dr. Azis, S.Pd., M.Pd.",
      namal2: null,
      kodemk: "20E01C330",
      namamk: "Pragmatik",
      semester: 3,
      kelas: "C",
      hari: 0,
      ruang: 0,
      masuk: null,
      sks: 3,
      prodi: "PBSI",
    },
    {
      id: 1747,
      nidn1: "0010117306",
      nidn2: "",
      namal1: "Prof. Dr. Azis, S.Pd., M.Pd.",
      namal2: null,
      kodemk: "20E01C330",
      namamk: "Pragmatik",
      semester: 3,
      kelas: "D",
      hari: 0,
      ruang: 0,
      masuk: null,
      sks: 3,
      prodi: "PBSI",
    },
    {
      id: 1748,
      nidn1: "0010117306",
      nidn2: "",
      namal1: "Prof. Dr. Azis, S.Pd., M.Pd.",
      namal2: null,
      kodemk: "20E01C330",
      namamk: "Pragmatik",
      semester: 3,
      kelas: "E",
      hari: 0,
      ruang: 0,
      masuk: null,
      sks: 3,
      prodi: "PBSI",
    },
    {
      id: 1749,
      nidn1: "0010117306",
      nidn2: "",
      namal1: "Prof. Dr. Azis, S.Pd., M.Pd.",
      namal2: null,
      kodemk: "20E01C330",
      namamk: "Pragmatik",
      semester: 3,
      kelas: "F",
      hari: 0,
      ruang: 0,
      masuk: null,
      sks: 3,
      prodi: "PBSI",
    },
    {
      id: 1750,
      nidn1: "0012098908",
      nidn2: "",
      namal1: "Asri Ismail, S.Pd., M.Pd.",
      namal2: null,
      kodemk: "20E01C331",
      namamk: "Kewirausahaan",
      semester: 3,
      kelas: "A",
      hari: 0,
      ruang: 0,
      masuk: null,
      sks: 3,
      prodi: "PBSI",
    },
    {
      id: 1751,
      nidn1: "0012098908",
      nidn2: "",
      namal1: "Asri Ismail, S.Pd., M.Pd.",
      namal2: null,
      kodemk: "20E01C331",
      namamk: "Kewirausahaan",
      semester: 3,
      kelas: "B",
      hari: 0,
      ruang: 0,
      masuk: null,
      sks: 3,
      prodi: "PBSI",
    },
    {
      id: 1752,
      nidn1: "0911038503",
      nidn2: "",
      namal1: "Dr. Asis Nojeng, S.Pd, M.Pd.",
      namal2: null,
      kodemk: "20E01C331",
      namamk: "Kewirausahaan",
      semester: 3,
      kelas: "C",
      hari: 0,
      ruang: 0,
      masuk: null,
      sks: 3,
      prodi: "PBSI",
    },
    {
      id: 1753,
      nidn1: "0918068601",
      nidn2: "",
      namal1: "Dr.  Hasriani, S.Pd., M.Pd.",
      namal2: null,
      kodemk: "20E01C331",
      namamk: "Kewirausahaan",
      semester: 3,
      kelas: "D",
      hari: 0,
      ruang: 0,
      masuk: null,
      sks: 3,
      prodi: "PBSI",
    },
    {
      id: 1754,
      nidn1: "0918068601",
      nidn2: "",
      namal1: "Dr.  Hasriani, S.Pd., M.Pd.",
      namal2: null,
      kodemk: "20E01C331",
      namamk: "Kewirausahaan",
      semester: 3,
      kelas: "E",
      hari: 0,
      ruang: 0,
      masuk: null,
      sks: 3,
      prodi: "PBSI",
    },
    {
      id: 1755,
      nidn1: "",
      nidn2: "",
      namal1: null,
      namal2: null,
      kodemk: "20E01C331",
      namamk: "Kewirausahaan",
      semester: 3,
      kelas: "F",
      hari: 0,
      ruang: 0,
      masuk: null,
      sks: 3,
      prodi: "PBSI",
    },
    {
      id: 1756,
      nidn1: "0027057506",
      nidn2: "",
      namal1: "Dr. Usman, S.Pd.,M.Pd.",
      namal2: null,
      kodemk: "20E01C541",
      namamk: "Menulis Kreatif",
      semester: 5,
      kelas: "A",
      hari: 0,
      ruang: 0,
      masuk: null,
      sks: 2,
      prodi: "PBSI",
    },
    {
      id: 1757,
      nidn1: "0027057506",
      nidn2: "",
      namal1: "Dr. Usman, S.Pd.,M.Pd.",
      namal2: null,
      kodemk: "20E01C541",
      namamk: "Menulis Kreatif",
      semester: 5,
      kelas: "B",
      hari: 0,
      ruang: 0,
      masuk: null,
      sks: 2,
      prodi: "PBSI",
    },
    {
      id: 1758,
      nidn1: "0027057506",
      nidn2: "",
      namal1: "Dr. Usman, S.Pd.,M.Pd.",
      namal2: null,
      kodemk: "20E01C541",
      namamk: "Menulis Kreatif",
      semester: 5,
      kelas: "C",
      hari: 0,
      ruang: 0,
      masuk: null,
      sks: 2,
      prodi: "PBSI",
    },
    {
      id: 1759,
      nidn1: "0028066308",
      nidn2: "",
      namal1: "Dr. Salam, M.Pd.",
      namal2: null,
      kodemk: "20E01C541",
      namamk: "Menulis Kreatif",
      semester: 5,
      kelas: "D",
      hari: 0,
      ruang: 0,
      masuk: null,
      sks: 2,
      prodi: "PBSI",
    },
    {
      id: 1760,
      nidn1: "0028066308",
      nidn2: "",
      namal1: "Dr. Salam, M.Pd.",
      namal2: null,
      kodemk: "20E01C541",
      namamk: "Menulis Kreatif",
      semester: 5,
      kelas: "E",
      hari: 0,
      ruang: 0,
      masuk: null,
      sks: 2,
      prodi: "PBSI",
    },
    {
      id: 1761,
      nidn1: "0029077905",
      nidn2: "",
      namal1: "Aswati Asri, S.Pd., M.Pd.",
      namal2: null,
      kodemk: "20E01C542",
      namamk: "Apresiasi Puisi",
      semester: 5,
      kelas: "A",
      hari: 0,
      ruang: 0,
      masuk: null,
      sks: 2,
      prodi: "PBSI",
    },
    {
      id: 1762,
      nidn1: "0029077905",
      nidn2: "",
      namal1: "Aswati Asri, S.Pd., M.Pd.",
      namal2: null,
      kodemk: "20E01C542",
      namamk: "Apresiasi Puisi",
      semester: 5,
      kelas: "B",
      hari: 0,
      ruang: 0,
      masuk: null,
      sks: 2,
      prodi: "PBSI",
    },
    {
      id: 1763,
      nidn1: "0029077905",
      nidn2: "",
      namal1: "Aswati Asri, S.Pd., M.Pd.",
      namal2: null,
      kodemk: "20E01C542",
      namamk: "Apresiasi Puisi",
      semester: 5,
      kelas: "C",
      hari: 0,
      ruang: 0,
      masuk: null,
      sks: 2,
      prodi: "PBSI",
    },
    {
      id: 1764,
      nidn1: "0911038503",
      nidn2: "",
      namal1: "Dr. Asis Nojeng, S.Pd, M.Pd.",
      namal2: null,
      kodemk: "20E01C542",
      namamk: "Apresiasi Puisi",
      semester: 5,
      kelas: "D",
      hari: 0,
      ruang: 0,
      masuk: null,
      sks: 2,
      prodi: "PBSI",
    },
    {
      id: 1765,
      nidn1: "0911038503",
      nidn2: "",
      namal1: "Dr. Asis Nojeng, S.Pd, M.Pd.",
      namal2: null,
      kodemk: "20E01C542",
      namamk: "Apresiasi Puisi",
      semester: 5,
      kelas: "E",
      hari: 0,
      ruang: 0,
      masuk: null,
      sks: 2,
      prodi: "PBSI",
    },
    {
      id: 1766,
      nidn1: "0024117104",
      nidn2: "",
      namal1: "Dr. Idawati, S.Pd., M.Pd.",
      namal2: null,
      kodemk: "20E01C543",
      namamk: "BIPA",
      semester: 5,
      kelas: "A",
      hari: 0,
      ruang: 0,
      masuk: null,
      sks: 2,
      prodi: "PBSI",
    },
    {
      id: 1767,
      nidn1: "0024117104",
      nidn2: "",
      namal1: "Dr. Idawati, S.Pd., M.Pd.",
      namal2: null,
      kodemk: "20E01C543",
      namamk: "BIPA",
      semester: 5,
      kelas: "B",
      hari: 0,
      ruang: 0,
      masuk: null,
      sks: 2,
      prodi: "PBSI",
    },
    {
      id: 1768,
      nidn1: "0024117104",
      nidn2: "",
      namal1: "Dr. Idawati, S.Pd., M.Pd.",
      namal2: null,
      kodemk: "20E01C543",
      namamk: "BIPA",
      semester: 5,
      kelas: "C",
      hari: 0,
      ruang: 0,
      masuk: null,
      sks: 2,
      prodi: "PBSI",
    },
    {
      id: 1769,
      nidn1: "0017087110",
      nidn2: "",
      namal1: "Dr. Ir. Abdul Azis, S.Pd.,M.Pd., M.T., IPM.",
      namal2: null,
      kodemk: "20E01C543",
      namamk: "BIPA",
      semester: 5,
      kelas: "D",
      hari: 0,
      ruang: 0,
      masuk: null,
      sks: 2,
      prodi: "PBSI",
    },
    {
      id: 1770,
      nidn1: "0017087110",
      nidn2: "",
      namal1: "Dr. Ir. Abdul Azis, S.Pd.,M.Pd., M.T., IPM.",
      namal2: null,
      kodemk: "20E01C543",
      namamk: "BIPA",
      semester: 5,
      kelas: "E",
      hari: 0,
      ruang: 0,
      masuk: null,
      sks: 2,
      prodi: "PBSI",
    },
    {
      id: 1771,
      nidn1: "0927038504",
      nidn2: "",
      namal1: "Dr. Sakaria, S.S., S.Pd., M.Pd.",
      namal2: null,
      kodemk: "20E01C544",
      namamk: "Teknologi Digital  dalam Pembelajaran",
      semester: 5,
      kelas: "A",
      hari: 0,
      ruang: 0,
      masuk: null,
      sks: 2,
      prodi: "PBSI",
    },
    {
      id: 1772,
      nidn1: "0927038504",
      nidn2: "",
      namal1: "Dr. Sakaria, S.S., S.Pd., M.Pd.",
      namal2: null,
      kodemk: "20E01C544",
      namamk: "Teknologi Digital  dalam Pembelajaran",
      semester: 5,
      kelas: "B",
      hari: 0,
      ruang: 0,
      masuk: null,
      sks: 2,
      prodi: "PBSI",
    },
    {
      id: 1773,
      nidn1: "0927038504",
      nidn2: "",
      namal1: "Dr. Sakaria, S.S., S.Pd., M.Pd.",
      namal2: null,
      kodemk: "20E01C544",
      namamk: "Teknologi Digital  dalam Pembelajaran",
      semester: 5,
      kelas: "C",
      hari: 0,
      ruang: 0,
      masuk: null,
      sks: 2,
      prodi: "PBSI",
    },
    {
      id: 1774,
      nidn1: "0017087110",
      nidn2: "",
      namal1: "Dr. Ir. Abdul Azis, S.Pd.,M.Pd., M.T., IPM.",
      namal2: null,
      kodemk: "20E01C544",
      namamk: "Teknologi Digital  dalam Pembelajaran",
      semester: 5,
      kelas: "D",
      hari: 0,
      ruang: 0,
      masuk: null,
      sks: 2,
      prodi: "PBSI",
    },
    {
      id: 1775,
      nidn1: "0017087110",
      nidn2: "",
      namal1: "Dr. Ir. Abdul Azis, S.Pd.,M.Pd., M.T., IPM.",
      namal2: null,
      kodemk: "20E01C544",
      namamk: "Teknologi Digital  dalam Pembelajaran",
      semester: 5,
      kelas: "E",
      hari: 0,
      ruang: 0,
      masuk: null,
      sks: 2,
      prodi: "PBSI",
    },
    {
      id: 1776,
      nidn1: "0025108802",
      nidn2: "",
      namal1: "Dr. Nurhusna, S.Pd.,M.Pd.",
      namal2: null,
      kodemk: "20E01C545",
      namamk: "Pengembangan Materi dan Media Pembelajaran BSI",
      semester: 5,
      kelas: "A",
      hari: 0,
      ruang: 0,
      masuk: null,
      sks: 3,
      prodi: "PBSI",
    },
    {
      id: 1777,
      nidn1: "0025108802",
      nidn2: "",
      namal1: "Dr. Nurhusna, S.Pd.,M.Pd.",
      namal2: null,
      kodemk: "20E01C545",
      namamk: "Pengembangan Materi dan Media Pembelajaran BSI",
      semester: 5,
      kelas: "B",
      hari: 0,
      ruang: 0,
      masuk: null,
      sks: 3,
      prodi: "PBSI",
    },
    {
      id: 1778,
      nidn1: "0024117104",
      nidn2: "",
      namal1: "Dr. Idawati, S.Pd., M.Pd.",
      namal2: null,
      kodemk: "20E01C545",
      namamk: "Pengembangan Materi dan Media Pembelajaran BSI",
      semester: 5,
      kelas: "C",
      hari: 0,
      ruang: 0,
      masuk: null,
      sks: 3,
      prodi: "PBSI",
    },
    {
      id: 1779,
      nidn1: "0927038504",
      nidn2: "",
      namal1: "Dr. Sakaria, S.S., S.Pd., M.Pd.",
      namal2: null,
      kodemk: "20E01C545",
      namamk: "Pengembangan Materi dan Media Pembelajaran BSI",
      semester: 5,
      kelas: "D",
      hari: 0,
      ruang: 0,
      masuk: null,
      sks: 3,
      prodi: "PBSI",
    },
    {
      id: 1780,
      nidn1: "0918068601",
      nidn2: "",
      namal1: "Dr.  Hasriani, S.Pd., M.Pd.",
      namal2: null,
      kodemk: "20E01C545",
      namamk: "Pengembangan Materi dan Media Pembelajaran BSI",
      semester: 5,
      kelas: "E",
      hari: 0,
      ruang: 0,
      masuk: null,
      sks: 3,
      prodi: "PBSI",
    },
    {
      id: 1781,
      nidn1: "0016065910",
      nidn2: "",
      namal1: "Prof. Dr. Ramly, M.Hum.",
      namal2: null,
      kodemk: "20E01C546",
      namamk: "Penelitian Pembelajaran BSI",
      semester: 5,
      kelas: "A",
      hari: 0,
      ruang: 0,
      masuk: null,
      sks: 3,
      prodi: "PBSI",
    },
    {
      id: 1782,
      nidn1: "0016065910",
      nidn2: "",
      namal1: "Prof. Dr. Ramly, M.Hum.",
      namal2: null,
      kodemk: "20E01C546",
      namamk: "Penelitian Pembelajaran BSI",
      semester: 5,
      kelas: "B",
      hari: 0,
      ruang: 0,
      masuk: null,
      sks: 3,
      prodi: "PBSI",
    },
    {
      id: 1783,
      nidn1: "0012067909",
      nidn2: "",
      namal1: "Prof. Dr. Sultan, S.Pd.,M.Pd.",
      namal2: null,
      kodemk: "20E01C546",
      namamk: "Penelitian Pembelajaran BSI",
      semester: 5,
      kelas: "C",
      hari: 0,
      ruang: 0,
      masuk: null,
      sks: 3,
      prodi: "PBSI",
    },
    {
      id: 1784,
      nidn1: "0012067909",
      nidn2: "",
      namal1: "Prof. Dr. Sultan, S.Pd.,M.Pd.",
      namal2: null,
      kodemk: "20E01C546",
      namamk: "Penelitian Pembelajaran BSI",
      semester: 5,
      kelas: "D",
      hari: 0,
      ruang: 0,
      masuk: null,
      sks: 3,
      prodi: "PBSI",
    },
    {
      id: 1785,
      nidn1: "0016025902",
      nidn2: "",
      namal1: "Prof. Dr. Sulastriningsih Djumingin, M.Hum.",
      namal2: null,
      kodemk: "20E01C546",
      namamk: "Penelitian Pembelajaran BSI",
      semester: 5,
      kelas: "E",
      hari: 0,
      ruang: 0,
      masuk: null,
      sks: 3,
      prodi: "PBSI",
    },
    {
      id: 1786,
      nidn1: "0031127506",
      nidn2: "",
      namal1: "Dr. H. Muhammad Saleh, S.Pd., M.Pd.",
      namal2: null,
      kodemk: "20E01C547",
      namamk: "Menulis Karya Ilmiah",
      semester: 5,
      kelas: "A",
      hari: 0,
      ruang: 0,
      masuk: null,
      sks: 3,
      prodi: "PBSI",
    },
    {
      id: 1787,
      nidn1: "0031127506",
      nidn2: "",
      namal1: "Dr. H. Muhammad Saleh, S.Pd., M.Pd.",
      namal2: null,
      kodemk: "20E01C547",
      namamk: "Menulis Karya Ilmiah",
      semester: 5,
      kelas: "B",
      hari: 0,
      ruang: 0,
      masuk: null,
      sks: 3,
      prodi: "PBSI",
    },
    {
      id: 1788,
      nidn1: "0031127506",
      nidn2: "",
      namal1: "Dr. H. Muhammad Saleh, S.Pd., M.Pd.",
      namal2: null,
      kodemk: "20E01C547",
      namamk: "Menulis Karya Ilmiah",
      semester: 5,
      kelas: "C",
      hari: 0,
      ruang: 0,
      masuk: null,
      sks: 3,
      prodi: "PBSI",
    },
    {
      id: 1789,
      nidn1: "0005058802",
      nidn2: "",
      namal1: "Dr. Abdul Haliq, S.Pd., M.Pd.",
      namal2: null,
      kodemk: "20E01C547",
      namamk: "Menulis Karya Ilmiah",
      semester: 5,
      kelas: "D",
      hari: 0,
      ruang: 0,
      masuk: null,
      sks: 3,
      prodi: "PBSI",
    },
    {
      id: 1790,
      nidn1: "0927038504",
      nidn2: "",
      namal1: "Dr. Sakaria, S.S., S.Pd., M.Pd.",
      namal2: null,
      kodemk: "20E01C547",
      namamk: "Menulis Karya Ilmiah",
      semester: 5,
      kelas: "E",
      hari: 0,
      ruang: 0,
      masuk: null,
      sks: 3,
      prodi: "PBSI",
    },
    {
      id: 1791,
      nidn1: "0013016805",
      nidn2: "",
      namal1: "Dr. Tuti Wijayanti, M.Pd.",
      namal2: null,
      kodemk: "20E01C548",
      namamk: "Menulis Buku Ajar",
      semester: 5,
      kelas: "A",
      hari: 0,
      ruang: 0,
      masuk: null,
      sks: 3,
      prodi: "PBSI",
    },
    {
      id: 1792,
      nidn1: "0013016805",
      nidn2: "",
      namal1: "Dr. Tuti Wijayanti, M.Pd.",
      namal2: null,
      kodemk: "20E01C548",
      namamk: "Menulis Buku Ajar",
      semester: 5,
      kelas: "B",
      hari: 0,
      ruang: 0,
      masuk: null,
      sks: 3,
      prodi: "PBSI",
    },
    {
      id: 1793,
      nidn1: "0028066308",
      nidn2: "",
      namal1: "Dr. Salam, M.Pd.",
      namal2: null,
      kodemk: "20E01C548",
      namamk: "Menulis Buku Ajar",
      semester: 5,
      kelas: "C",
      hari: 0,
      ruang: 0,
      masuk: null,
      sks: 3,
      prodi: "PBSI",
    },
    {
      id: 1794,
      nidn1: "0031126337",
      nidn2: "",
      namal1: "Dr. Mayong, M.Pd.",
      namal2: null,
      kodemk: "20E01C548",
      namamk: "Menulis Buku Ajar",
      semester: 5,
      kelas: "D",
      hari: 0,
      ruang: 0,
      masuk: null,
      sks: 3,
      prodi: "PBSI",
    },
    {
      id: 1795,
      nidn1: "0031126337",
      nidn2: "",
      namal1: "Dr. Mayong, M.Pd.",
      namal2: null,
      kodemk: "20E01C548",
      namamk: "Menulis Buku Ajar",
      semester: 5,
      kelas: "E",
      hari: 0,
      ruang: 0,
      masuk: null,
      sks: 3,
      prodi: "PBSI",
    },
    {
      id: 1808,
      nidn1: "0028086908",
      nidn2: "",
      namal1: "Dr. Asia M., S.S.,M.Pd.",
      namal2: null,
      kodemk: "20E03C101",
      namamk: "Pengantar Linguistik",
      semester: 1,
      kelas: "A",
      hari: 0,
      ruang: 0,
      masuk: null,
      sks: 3,
      prodi: "PBSD",
    },
    {
      id: 1809,
      nidn1: "0028086908",
      nidn2: "",
      namal1: "Dr. Asia M., S.S.,M.Pd.",
      namal2: null,
      kodemk: "20E03C101",
      namamk: "Pengantar Linguistik",
      semester: 1,
      kelas: "B",
      hari: 0,
      ruang: 0,
      masuk: null,
      sks: 3,
      prodi: "PBSD",
    },
    {
      id: 1810,
      nidn1: "0915018704",
      nidn2: "",
      namal1: "Ita Rosvita, S.S., M.Hum.",
      namal2: null,
      kodemk: "20E03C101",
      namamk: "Pengantar Linguistik",
      semester: 1,
      kelas: "C",
      hari: 0,
      ruang: 0,
      masuk: null,
      sks: 3,
      prodi: "PBSD",
    },
    {
      id: 1811,
      nidn1: "0018056510",
      nidn2: "",
      namal1: "Dr. Syamsudduha, M.Hum.",
      namal2: null,
      kodemk: "20E03C102",
      namamk: "Fonologi Bahasa Bugis",
      semester: 1,
      kelas: "A",
      hari: 0,
      ruang: 0,
      masuk: null,
      sks: 3,
      prodi: "PBSD",
    },
    {
      id: 1812,
      nidn1: "0031126445",
      nidn2: "",
      namal1: "Prof. Dr. Hj. Kembong Daeng, M.Hum.",
      namal2: null,
      kodemk: "20E03C103",
      namamk: "Fonologi Bahasa Makassar",
      semester: 1,
      kelas: "B",
      hari: 0,
      ruang: 0,
      masuk: null,
      sks: 3,
      prodi: "PBSD",
    },
    {
      id: 1813,
      nidn1: "0029089901",
      nidn2: "",
      namal1: "Ilma Rahim, S.Pd., M.Pd.",
      namal2: null,
      kodemk: "20E03C103",
      namamk: "Fonologi Bahasa Makassar",
      semester: 1,
      kelas: "C",
      hari: 0,
      ruang: 0,
      masuk: null,
      sks: 3,
      prodi: "PBSD",
    },
    {
      id: 1814,
      nidn1: "0011057406",
      nidn2: "",
      namal1: "Andi Fatimah Yunus, M.Pd.",
      namal2: null,
      kodemk: "20E03C104",
      namamk: "Marengkalinga",
      semester: 1,
      kelas: "A",
      hari: 0,
      ruang: 0,
      masuk: null,
      sks: 3,
      prodi: "PBSD",
    },
    {
      id: 1815,
      nidn1: "0002079502",
      nidn2: "",
      namal1: "Dedi Gunawan Saputra, S.Pd., M.M., M.Pd.",
      namal2: null,
      kodemk: "20E03C105",
      namamk: "Appinaknak",
      semester: 1,
      kelas: "B",
      hari: 0,
      ruang: 0,
      masuk: null,
      sks: 3,
      prodi: "PBSD",
    },
    {
      id: 1816,
      nidn1: "0028086908",
      nidn2: "",
      namal1: "Dr. Asia M., S.S.,M.Pd.",
      namal2: null,
      kodemk: "20E03C105",
      namamk: "Appinaknak",
      semester: 1,
      kelas: "C",
      hari: 0,
      ruang: 0,
      masuk: null,
      sks: 3,
      prodi: "PBSD",
    },
    {
      id: 1817,
      nidn1: "0912108902",
      nidn2: "",
      namal1: "Fitriansal, S.Pd., M.Pd.",
      namal2: null,
      kodemk: "20E03C106",
      namamk: "Teori dan Sejarah Sastra",
      semester: 1,
      kelas: "A",
      hari: 0,
      ruang: 0,
      masuk: null,
      sks: 3,
      prodi: "PBSD",
    },
    {
      id: 1818,
      nidn1: "0025107203",
      nidn2: "",
      namal1: "Dr. Hajrah, S.S., M.Pd.",
      namal2: null,
      kodemk: "20E03C106",
      namamk: "Teori dan Sejarah Sastra",
      semester: 1,
      kelas: "B",
      hari: 0,
      ruang: 0,
      masuk: null,
      sks: 3,
      prodi: "PBSD",
    },
    {
      id: 1819,
      nidn1: "0025107203",
      nidn2: "",
      namal1: "Dr. Hajrah, S.S., M.Pd.",
      namal2: null,
      kodemk: "20E03C106",
      namamk: "Teori dan Sejarah Sastra",
      semester: 1,
      kelas: "C",
      hari: 0,
      ruang: 0,
      masuk: null,
      sks: 3,
      prodi: "PBSD",
    },
    {
      id: 1821,
      nidn1: "0029077905",
      nidn2: "",
      namal1: "Aswati Asri, S.Pd., M.Pd.",
      namal2: null,
      kodemk: "20E03C107",
      namamk: "Bahasa Bugis",
      semester: 1,
      kelas: "B",
      hari: 0,
      ruang: 0,
      masuk: null,
      sks: 2,
      prodi: "PBSD",
    },
    {
      id: 1822,
      nidn1: "0029077905",
      nidn2: "",
      namal1: "Aswati Asri, S.Pd., M.Pd.",
      namal2: null,
      kodemk: "20E03C107",
      namamk: "Bahasa Bugis",
      semester: 1,
      kelas: "C",
      hari: 0,
      ruang: 0,
      masuk: null,
      sks: 2,
      prodi: "PBSD",
    },
    {
      id: 1820,
      nidn1: "0002079502",
      nidn2: "",
      namal1: "Dedi Gunawan Saputra, S.Pd., M.M., M.Pd.",
      namal2: null,
      kodemk: "20E03C108",
      namamk: "Bahasa Makassar",
      semester: 1,
      kelas: "A",
      hari: 0,
      ruang: 0,
      masuk: null,
      sks: 2,
      prodi: "PBSD",
    },
    {
      id: 1823,
      nidn1: "0011057406",
      nidn2: "",
      namal1: "Andi Fatimah Yunus, M.Pd.",
      namal2: null,
      kodemk: "20E03C318",
      namamk: "Sintaksis Bahasa Bugis",
      semester: 3,
      kelas: "A",
      hari: 0,
      ruang: 0,
      masuk: null,
      sks: 3,
      prodi: "PBSD",
    },
    {
      id: 1824,
      nidn1: "0019096015",
      nidn2: "",
      namal1: "Prof. Dr. Hj. Johar Amir, M.Hum.",
      namal2: null,
      kodemk: "20E03C319",
      namamk: "Sintaksis Bahasa Makasar",
      semester: 3,
      kelas: "B",
      hari: 0,
      ruang: 0,
      masuk: null,
      sks: 3,
      prodi: "PBSD",
    },
    {
      id: 1825,
      nidn1: "0011057406",
      nidn2: "",
      namal1: "Andi Fatimah Yunus, M.Pd.",
      namal2: null,
      kodemk: "20E03C320",
      namamk: "Semantik Bahasa Bugis",
      semester: 3,
      kelas: "A",
      hari: 0,
      ruang: 0,
      masuk: null,
      sks: 3,
      prodi: "PBSD",
    },
    {
      id: 1826,
      nidn1: "0019096015",
      nidn2: "",
      namal1: "Prof. Dr. Hj. Johar Amir, M.Hum.",
      namal2: null,
      kodemk: "20E03C321",
      namamk: "Semantik Bahasa Makassar",
      semester: 3,
      kelas: "B",
      hari: 0,
      ruang: 0,
      masuk: null,
      sks: 3,
      prodi: "PBSD",
    },
    {
      id: 1827,
      nidn1: "0011057406",
      nidn2: "",
      namal1: "Andi Fatimah Yunus, M.Pd.",
      namal2: null,
      kodemk: "20E03C322",
      namamk: "Marukiq",
      semester: 3,
      kelas: "A",
      hari: 0,
      ruang: 0,
      masuk: null,
      sks: 3,
      prodi: "PBSD",
    },
    {
      id: 1828,
      nidn1: "0027086405",
      nidn2: "",
      namal1: "Dr. Abd. Rahim, SE, M.Pd.",
      namal2: null,
      kodemk: "20E03C323",
      namamk: "Anggukirik",
      semester: 3,
      kelas: "B",
      hari: 0,
      ruang: 0,
      masuk: null,
      sks: 3,
      prodi: "PBSD",
    },
    {
      id: 1829,
      nidn1: "0018056510",
      nidn2: "",
      namal1: "Dr. Syamsudduha, M.Hum.",
      namal2: null,
      kodemk: "20E03C324",
      namamk: "Telaah Kurikulum dan Buku Teks Bahasa Bugis",
      semester: 3,
      kelas: "A",
      hari: 0,
      ruang: 0,
      masuk: null,
      sks: 3,
      prodi: "PBSD",
    },
    {
      id: 1830,
      nidn1: "0029089901",
      nidn2: "",
      namal1: "Ilma Rahim, S.Pd., M.Pd.",
      namal2: null,
      kodemk: "20E03C325",
      namamk: "Telaah Kurikulum dan Buku Teks Bahasa Makassar",
      semester: 3,
      kelas: "B",
      hari: 0,
      ruang: 0,
      masuk: null,
      sks: 3,
      prodi: "PBSD",
    },
    {
      id: 1831,
      nidn1: "0031126445",
      nidn2: "",
      namal1: "Prof. Dr. Hj. Kembong Daeng, M.Hum.",
      namal2: null,
      kodemk: "20E03C326",
      namamk: "Metode dan Strategi Pembelajaran Bahasa Daerah",
      semester: 3,
      kelas: "A",
      hari: 0,
      ruang: 0,
      masuk: null,
      sks: 3,
      prodi: "PBSD",
    },
    {
      id: 1832,
      nidn1: "0031126445",
      nidn2: "",
      namal1: "Prof. Dr. Hj. Kembong Daeng, M.Hum.",
      namal2: null,
      kodemk: "20E03C326",
      namamk: "Metode dan Strategi Pembelajaran Bahasa Daerah",
      semester: 3,
      kelas: "B",
      hari: 0,
      ruang: 0,
      masuk: null,
      sks: 3,
      prodi: "PBSD",
    },
    {
      id: 1833,
      nidn1: "0029077905",
      nidn2: "",
      namal1: "Aswati Asri, S.Pd., M.Pd.",
      namal2: null,
      kodemk: "20E03C327",
      namamk: "Menulis Kreatif Bahasa Bugis-Makassar",
      semester: 3,
      kelas: "A",
      hari: 0,
      ruang: 0,
      masuk: null,
      sks: 2,
      prodi: "PBSD",
    },
    {
      id: 1834,
      nidn1: "0029077905",
      nidn2: "",
      namal1: "Aswati Asri, S.Pd., M.Pd.",
      namal2: null,
      kodemk: "20E03C327",
      namamk: "Menulis Kreatif Bahasa Bugis-Makassar",
      semester: 3,
      kelas: "B",
      hari: 0,
      ruang: 0,
      masuk: null,
      sks: 2,
      prodi: "PBSD",
    },
    {
      id: 1835,
      nidn1: "0018056510",
      nidn2: "",
      namal1: "Dr. Syamsudduha, M.Hum.",
      namal2: null,
      kodemk: "20E03C328",
      namamk: "Perencanaan Pembelajaran Bahasa Bugis-Makassar",
      semester: 3,
      kelas: "A",
      hari: 0,
      ruang: 0,
      masuk: null,
      sks: 2,
      prodi: "PBSD",
    },
    {
      id: 1836,
      nidn1: "0016129206",
      nidn2: "",
      namal1: "Muhammad Ilham, S.Pd., M.Pd.",
      namal2: null,
      kodemk: "20E03C328",
      namamk: "Perencanaan Pembelajaran Bahasa Bugis-Makassar",
      semester: 3,
      kelas: "B",
      hari: 0,
      ruang: 0,
      masuk: null,
      sks: 2,
      prodi: "PBSD",
    },
    {
      id: 1837,
      nidn1: "0029077905",
      nidn2: "",
      namal1: "Aswati Asri, S.Pd., M.Pd.",
      namal2: null,
      kodemk: "20E03C329",
      namamk: "Apresiasi Prosa Fiksi",
      semester: 3,
      kelas: "A",
      hari: 0,
      ruang: 0,
      masuk: null,
      sks: 3,
      prodi: "PBSD",
    },
    {
      id: 1838,
      nidn1: "0029077905",
      nidn2: "",
      namal1: "Aswati Asri, S.Pd., M.Pd.",
      namal2: null,
      kodemk: "20E03C329",
      namamk: "Apresiasi Prosa Fiksi",
      semester: 3,
      kelas: "B",
      hari: 0,
      ruang: 0,
      masuk: null,
      sks: 3,
      prodi: "PBSD",
    },
    {
      id: 1839,
      nidn1: "0915018704",
      nidn2: "",
      namal1: "Ita Rosvita, S.S., M.Hum.",
      namal2: null,
      kodemk: "20E03C330",
      namamk: "Pappaseng",
      semester: 3,
      kelas: "A",
      hari: 0,
      ruang: 0,
      masuk: null,
      sks: 2,
      prodi: "PBSD",
    },
    {
      id: 1840,
      nidn1: "0027086405",
      nidn2: "",
      namal1: "Dr. Abd. Rahim, SE, M.Pd.",
      namal2: null,
      kodemk: "20E03C331",
      namamk: "Pappasang",
      semester: 3,
      kelas: "B",
      hari: 0,
      ruang: 0,
      masuk: null,
      sks: 2,
      prodi: "PBSD",
    },
    {
      id: 1841,
      nidn1: "0016129206",
      nidn2: "",
      namal1: "Muhammad Ilham, S.Pd., M.Pd.",
      namal2: null,
      kodemk: "20E03C5013",
      namamk: "Sosiolinguitik",
      semester: 5,
      kelas: "A",
      hari: 0,
      ruang: 0,
      masuk: null,
      sks: 3,
      prodi: "PBSD",
    },
    {
      id: 1842,
      nidn1: "0019096015",
      nidn2: "",
      namal1: "Prof. Dr. Hj. Johar Amir, M.Hum.",
      namal2: null,
      kodemk: "20E03C5013",
      namamk: "Sosiolinguitik",
      semester: 5,
      kelas: "B",
      hari: 0,
      ruang: 0,
      masuk: null,
      sks: 3,
      prodi: "PBSD",
    },
    {
      id: 1843,
      nidn1: "0028086908",
      nidn2: "",
      namal1: "Dr. Asia M., S.S.,M.Pd.",
      namal2: null,
      kodemk: "20E03C5023",
      namamk: "Psikolinguistik",
      semester: 5,
      kelas: "A",
      hari: 0,
      ruang: 0,
      masuk: null,
      sks: 3,
      prodi: "PBSD",
    },
    {
      id: 1844,
      nidn1: "0016129206",
      nidn2: "",
      namal1: "Muhammad Ilham, S.Pd., M.Pd.",
      namal2: null,
      kodemk: "20E03C5023",
      namamk: "Psikolinguistik",
      semester: 5,
      kelas: "B",
      hari: 0,
      ruang: 0,
      masuk: null,
      sks: 3,
      prodi: "PBSD",
    },
    {
      id: 1845,
      nidn1: "0025107203",
      nidn2: "",
      namal1: "Dr. Hajrah, S.S., M.Pd.",
      namal2: null,
      kodemk: "20E03C5032",
      namamk: "Teori Belajar Bahasa",
      semester: 5,
      kelas: "A",
      hari: 0,
      ruang: 0,
      masuk: null,
      sks: 2,
      prodi: "PBSD",
    },
    {
      id: 1846,
      nidn1: "0025107203",
      nidn2: "",
      namal1: "Dr. Hajrah, S.S., M.Pd.",
      namal2: null,
      kodemk: "20E03C5032",
      namamk: "Teori Belajar Bahasa",
      semester: 5,
      kelas: "B",
      hari: 0,
      ruang: 0,
      masuk: null,
      sks: 2,
      prodi: "PBSD",
    },
    {
      id: 1847,
      nidn1: "0017087107",
      nidn2: "",
      namal1: "Dr. Andi Agussalim Aj., M.Hum.",
      namal2: null,
      kodemk: "20E03C5043",
      namamk: "Filologi",
      semester: 5,
      kelas: "A",
      hari: 0,
      ruang: 0,
      masuk: null,
      sks: 3,
      prodi: "PBSD",
    },
    {
      id: 1848,
      nidn1: "0030126012",
      nidn2: "",
      namal1: "Prof. Dr. H. Muhammad Rapi , M.S.",
      namal2: null,
      kodemk: "20E03C5043",
      namamk: "Filologi",
      semester: 5,
      kelas: "B",
      hari: 0,
      ruang: 0,
      masuk: null,
      sks: 3,
      prodi: "PBSD",
    },
    {
      id: 1849,
      nidn1: "0017087107",
      nidn2: "",
      namal1: "Dr. Andi Agussalim Aj., M.Hum.",
      namal2: null,
      kodemk: "20E03C5053",
      namamk: "Folklor",
      semester: 5,
      kelas: "A",
      hari: 0,
      ruang: 0,
      masuk: null,
      sks: 3,
      prodi: "PBSD",
    },
    {
      id: 1850,
      nidn1: "0017087107",
      nidn2: "",
      namal1: "Dr. Andi Agussalim Aj., M.Hum.",
      namal2: null,
      kodemk: "20E03C5053",
      namamk: "Folklor",
      semester: 5,
      kelas: "B",
      hari: 0,
      ruang: 0,
      masuk: null,
      sks: 3,
      prodi: "PBSD",
    },
    {
      id: 1851,
      nidn1: "0025107203",
      nidn2: "",
      namal1: "Dr. Hajrah, S.S., M.Pd.",
      namal2: null,
      kodemk: "20E03C5062",
      namamk: "Sastra Nusantara",
      semester: 5,
      kelas: "A",
      hari: 0,
      ruang: 0,
      masuk: null,
      sks: 2,
      prodi: "PBSD",
    },
    {
      id: 1852,
      nidn1: "0025107203",
      nidn2: "",
      namal1: "Dr. Hajrah, S.S., M.Pd.",
      namal2: null,
      kodemk: "20E03C5062",
      namamk: "Sastra Nusantara",
      semester: 5,
      kelas: "B",
      hari: 0,
      ruang: 0,
      masuk: null,
      sks: 2,
      prodi: "PBSD",
    },
    {
      id: 1853,
      nidn1: "0912108902",
      nidn2: "",
      namal1: "Fitriansal, S.Pd., M.Pd.",
      namal2: null,
      kodemk: "20E03C5072",
      namamk: "Sinematografi",
      semester: 5,
      kelas: "A",
      hari: 0,
      ruang: 0,
      masuk: null,
      sks: 2,
      prodi: "PBSD",
    },
    {
      id: 1854,
      nidn1: "0912108902",
      nidn2: "",
      namal1: "Fitriansal, S.Pd., M.Pd.",
      namal2: null,
      kodemk: "20E03C5072",
      namamk: "Sinematografi",
      semester: 5,
      kelas: "B",
      hari: 0,
      ruang: 0,
      masuk: null,
      sks: 2,
      prodi: "PBSD",
    },
    {
      id: 1855,
      nidn1: "0027086405",
      nidn2: "",
      namal1: "Dr. Abd. Rahim, SE, M.Pd.",
      namal2: null,
      kodemk: "20E03C5082",
      namamk: "Manusia dan Kebudayaan Sulawesi Selatan",
      semester: 5,
      kelas: "A",
      hari: 0,
      ruang: 0,
      masuk: null,
      sks: 2,
      prodi: "PBSD",
    },
    {
      id: 1856,
      nidn1: "0017087107",
      nidn2: "",
      namal1: "Dr. Andi Agussalim Aj., M.Hum.",
      namal2: null,
      kodemk: "20E03C5092",
      namamk: "Kesenian Sulawesi Selatan",
      semester: 5,
      kelas: "A",
      hari: 0,
      ruang: 0,
      masuk: null,
      sks: 2,
      prodi: "PBSD",
    },
    {
      id: 1857,
      nidn1: "0017087107",
      nidn2: "",
      namal1: "Dr. Andi Agussalim Aj., M.Hum.",
      namal2: null,
      kodemk: "20E03C5092",
      namamk: "Kesenian Sulawesi Selatan",
      semester: 5,
      kelas: "B",
      hari: 0,
      ruang: 0,
      masuk: null,
      sks: 2,
      prodi: "PBSD",
    },
    {
      id: 1858,
      nidn1: "0010036805",
      nidn2: "",
      namal1: "Dr. Juanda, M.Hum.",
      namal2: null,
      kodemk: "20E03C5102",
      namamk: "Bahasa Inggris",
      semester: 5,
      kelas: "A",
      hari: 0,
      ruang: 0,
      masuk: null,
      sks: 2,
      prodi: "PBSD",
    },
    {
      id: 1859,
      nidn1: "0010036805",
      nidn2: "",
      namal1: "Dr. Juanda, M.Hum.",
      namal2: null,
      kodemk: "20E03C5102",
      namamk: "Bahasa Inggris",
      semester: 5,
      kelas: "B",
      hari: 0,
      ruang: 0,
      masuk: null,
      sks: 2,
      prodi: "PBSD",
    },
    {
      id: 1697,
      nidn1: "1",
      nidn2: "",
      namal1: "MKDU PAI",
      namal2: null,
      kodemk: "20X01C001",
      namamk: "Pendidikan Agama Islam",
      semester: 1,
      kelas: "A",
      hari: 0,
      ruang: 0,
      masuk: null,
      sks: 2,
      prodi: "PBSI",
    },
    {
      id: 1698,
      nidn1: "1",
      nidn2: "",
      namal1: "MKDU PAI",
      namal2: null,
      kodemk: "20X01C001",
      namamk: "Pendidikan Agama Islam",
      semester: 1,
      kelas: "B",
      hari: 0,
      ruang: 0,
      masuk: null,
      sks: 2,
      prodi: "PBSI",
    },
    {
      id: 1699,
      nidn1: "1",
      nidn2: "",
      namal1: "MKDU PAI",
      namal2: null,
      kodemk: "20X01C001",
      namamk: "Pendidikan Agama Islam",
      semester: 1,
      kelas: "C",
      hari: 0,
      ruang: 0,
      masuk: null,
      sks: 2,
      prodi: "PBSI",
    },
    {
      id: 1700,
      nidn1: "1",
      nidn2: "",
      namal1: "MKDU PAI",
      namal2: null,
      kodemk: "20X01C001",
      namamk: "Pendidikan Agama Islam",
      semester: 1,
      kelas: "D",
      hari: 0,
      ruang: 0,
      masuk: null,
      sks: 2,
      prodi: "PBSI",
    },
    {
      id: 1701,
      nidn1: "1",
      nidn2: "",
      namal1: "MKDU PAI",
      namal2: null,
      kodemk: "20X01C001",
      namamk: "Pendidikan Agama Islam",
      semester: 1,
      kelas: "E",
      hari: 0,
      ruang: 0,
      masuk: null,
      sks: 2,
      prodi: "PBSI",
    },
    {
      id: 1702,
      nidn1: "1",
      nidn2: "",
      namal1: "MKDU PAI",
      namal2: null,
      kodemk: "20X01C001",
      namamk: "Pendidikan Agama Islam",
      semester: 1,
      kelas: "F",
      hari: 0,
      ruang: 0,
      masuk: null,
      sks: 2,
      prodi: "PBSI",
    },
    {
      id: 1703,
      nidn1: "1",
      nidn2: "",
      namal1: "MKDU PAI",
      namal2: null,
      kodemk: "20X01C001",
      namamk: "Pendidikan Agama Islam",
      semester: 1,
      kelas: "G",
      hari: 0,
      ruang: 0,
      masuk: null,
      sks: 2,
      prodi: "PBSI",
    },
    {
      id: 1690,
      nidn1: "0918068601",
      nidn2: "",
      namal1: "Dr.  Hasriani, S.Pd., M.Pd.",
      namal2: null,
      kodemk: "20X01C009",
      namamk: "Bahasa Indonesia",
      semester: 1,
      kelas: "A",
      hari: 0,
      ruang: 0,
      masuk: null,
      sks: 2,
      prodi: "PBSI",
    },
    {
      id: 1691,
      nidn1: "0022049801",
      nidn2: "",
      namal1: "Muh. Bahly Basri, S.Pd., M.Pd.",
      namal2: null,
      kodemk: "20X01C009",
      namamk: "Bahasa Indonesia",
      semester: 1,
      kelas: "B",
      hari: 0,
      ruang: 0,
      masuk: null,
      sks: 2,
      prodi: "PBSI",
    },
    {
      id: 1692,
      nidn1: "0911038503",
      nidn2: "",
      namal1: "Dr. Asis Nojeng, S.Pd, M.Pd.",
      namal2: null,
      kodemk: "20X01C009",
      namamk: "Bahasa Indonesia",
      semester: 1,
      kelas: "C",
      hari: 0,
      ruang: 0,
      masuk: null,
      sks: 2,
      prodi: "PBSI",
    },
    {
      id: 1693,
      nidn1: "0023069601",
      nidn2: "",
      namal1: "Shafariana, S.Pd., M.Pd.",
      namal2: null,
      kodemk: "20X01C009",
      namamk: "Bahasa Indonesia",
      semester: 1,
      kelas: "D",
      hari: 0,
      ruang: 0,
      masuk: null,
      sks: 2,
      prodi: "PBSI",
    },
    {
      id: 1694,
      nidn1: "0030129203",
      nidn2: "",
      namal1: "Rizki Herdiani, M. Pd.",
      namal2: null,
      kodemk: "20X01C009",
      namamk: "Bahasa Indonesia",
      semester: 1,
      kelas: "E",
      hari: 0,
      ruang: 0,
      masuk: null,
      sks: 2,
      prodi: "PBSI",
    },
    {
      id: 1695,
      nidn1: "0012098908",
      nidn2: "",
      namal1: "Asri Ismail, S.Pd., M.Pd.",
      namal2: null,
      kodemk: "20X01C009",
      namamk: "Bahasa Indonesia",
      semester: 1,
      kelas: "F",
      hari: 0,
      ruang: 0,
      masuk: null,
      sks: 2,
      prodi: "PBSI",
    },
    {
      id: 1696,
      nidn1: "0016129206",
      nidn2: "",
      namal1: "Muhammad Ilham, S.Pd., M.Pd.",
      namal2: null,
      kodemk: "20X01C009",
      namamk: "Bahasa Indonesia",
      semester: 1,
      kelas: "G",
      hari: 0,
      ruang: 0,
      masuk: null,
      sks: 2,
      prodi: "PBSI",
    },
    {
      id: 1799,
      nidn1: "2",
      nidn2: "",
      namal1: "MKDU PKN",
      namal2: null,
      kodemk: "20X03C008",
      namamk: "Pendidikan Kewarganegaraan",
      semester: 1,
      kelas: "A",
      hari: 0,
      ruang: 0,
      masuk: null,
      sks: 2,
      prodi: "PBSD",
    },
    {
      id: 1800,
      nidn1: "2",
      nidn2: "",
      namal1: "MKDU PKN",
      namal2: null,
      kodemk: "20X03C008",
      namamk: "Pendidikan Kewarganegaraan",
      semester: 1,
      kelas: "B",
      hari: 0,
      ruang: 0,
      masuk: null,
      sks: 2,
      prodi: "PBSD",
    },
    {
      id: 1801,
      nidn1: "2",
      nidn2: "",
      namal1: "MKDU PKN",
      namal2: null,
      kodemk: "20X03C008",
      namamk: "Pendidikan Kewarganegaraan",
      semester: 1,
      kelas: "C",
      hari: 0,
      ruang: 0,
      masuk: null,
      sks: 2,
      prodi: "PBSD",
    },
    {
      id: 1805,
      nidn1: "0027086405",
      nidn2: "",
      namal1: "Dr. Abd. Rahim, SE, M.Pd.",
      namal2: null,
      kodemk: "20X03C011",
      namamk: "Pengantar Pendidikan",
      semester: 1,
      kelas: "A",
      hari: 0,
      ruang: 0,
      masuk: null,
      sks: 2,
      prodi: "PBSD",
    },
    {
      id: 1806,
      nidn1: "0029089901",
      nidn2: "",
      namal1: "Ilma Rahim, S.Pd., M.Pd.",
      namal2: null,
      kodemk: "20X03C011",
      namamk: "Pengantar Pendidikan",
      semester: 1,
      kelas: "B",
      hari: 0,
      ruang: 0,
      masuk: null,
      sks: 2,
      prodi: "PBSD",
    },
    {
      id: 1807,
      nidn1: "0027086405",
      nidn2: "",
      namal1: "Dr. Abd. Rahim, SE, M.Pd.",
      namal2: null,
      kodemk: "20X03C011",
      namamk: "Pengantar Pendidikan",
      semester: 1,
      kelas: "C",
      hari: 0,
      ruang: 0,
      masuk: null,
      sks: 2,
      prodi: "PBSD",
    },
    {
      id: 1802,
      nidn1: "0018056510",
      nidn2: "",
      namal1: "Dr. Syamsudduha, M.Hum.",
      namal2: null,
      kodemk: "20X03C013",
      namamk: "Belajar dan Pembelajaran",
      semester: 1,
      kelas: "A",
      hari: 0,
      ruang: 0,
      masuk: null,
      sks: 2,
      prodi: "PBSD",
    },
    {
      id: 1803,
      nidn1: "0018056510",
      nidn2: "",
      namal1: "Dr. Syamsudduha, M.Hum.",
      namal2: null,
      kodemk: "20X03C013",
      namamk: "Belajar dan Pembelajaran",
      semester: 1,
      kelas: "B",
      hari: 0,
      ruang: 0,
      masuk: null,
      sks: 2,
      prodi: "PBSD",
    },
    {
      id: 1804,
      nidn1: "0002079502",
      nidn2: "",
      namal1: "Dedi Gunawan Saputra, S.Pd., M.M., M.Pd.",
      namal2: null,
      kodemk: "20X03C013",
      namamk: "Belajar dan Pembelajaran",
      semester: 1,
      kelas: "C",
      hari: 0,
      ruang: 0,
      masuk: null,
      sks: 2,
      prodi: "PBSD",
    },
    {
      id: 1796,
      nidn1: "panca01",
      nidn2: "",
      namal1: "MKDU Pancasila",
      namal2: null,
      kodemk: "20X03C014",
      namamk: "Profesi Kependidikan",
      semester: 2,
      kelas: "A",
      hari: 0,
      ruang: 0,
      masuk: null,
      sks: 2,
      prodi: "PBSD",
    },
    {
      id: 1797,
      nidn1: "panca01",
      nidn2: "",
      namal1: "MKDU Pancasila",
      namal2: null,
      kodemk: "20X03C014",
      namamk: "Profesi Kependidikan",
      semester: 2,
      kelas: "B",
      hari: 0,
      ruang: 0,
      masuk: null,
      sks: 2,
      prodi: "PBSD",
    },
    {
      id: 1798,
      nidn1: "panca01",
      nidn2: "",
      namal1: "MKDU Pancasila",
      namal2: null,
      kodemk: "20X03C014",
      namamk: "Profesi Kependidikan",
      semester: 2,
      kelas: "C",
      hari: 0,
      ruang: 0,
      masuk: null,
      sks: 2,
      prodi: "PBSD",
    },
  ],
};
